mod chat;
mod chat_interaction;
mod chats_list;
pub mod dashboard;
mod events;
mod jobs;
mod peers;
mod unroller;
mod session_control;
mod tools_list;
mod traces;

pub use chat::ChatWidget as Chat;
pub use chat_interaction::ChatInteraction;
pub use chats_list::ChatsListWidget as ChatsList;
pub use events::EventsWidget as Events;
pub use jobs::JobsWidget as Jobs;
pub use peers::PeersWidget as Peers;
pub use unroller::UnrollerSummaryWidget as UnrollerSummary;
pub use session_control::SessionControlWidget as SessionControl;
pub use tools_list::ToolsListWidget as ToolsList;
pub use traces::TracesWidget as Traces;
